#!/bin/bash

declare -a cydia
cydia=($CYDIA)

if [[ $1 == install ]]; then
    /usr/libexec/cydia/move.sh /Library/Themes
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    fi
elif [[ $1 == upgrade ]]; then
    if [[ -e /Applications/WinterBoard.app/pledit ]]; then
        /Applications/WinterBoard.app/pledit /System/Library/LaunchDaemons/com.apple.SpringBoard.plist \
            -r /Applications/WinterBoard.app/WinterBoard.dylib
        if [[ ${CYDIA+@} ]]; then
            eval "echo 'finish:reload' >&${cydia[0]}"
        fi
    else
        if [[ ${CYDIA+@} ]]; then
            eval "echo 'finish:restart' >&${cydia[0]}"
        fi
    fi
fi

exit 0
